import { UserInfoBase } from './user_info_base';

export interface PersonalUserInfo extends UserInfoBase {
    result: string,
    errmsg: string,
    officefax: string,
    birthday: string,
    sex: string,
    telephone2: string,
    idtype: string,
    userid: string,
    officialtype: string,
    servicecontent: string,
    city: string,
    loginname: string,
    username: string,
    officerlicense: string,
    useable: string,
    province: string,
    permitlicense: string,
    official: string,
    companysize: string,
    companypro: string,
    companydesc: string,
    homephone: string,
    companyalias: string,
    firmname: string,
    authlevel: string,
    companytype: string,
    orgcoding: string,
    mobile2: string,
    postcode: string,
    homeaddress: string,
    companyname: string,
    nation: string,
    country: string,
    officenum: string,
    officeaddress: string,
    headpicture: string,
    idnum: string,
    email: string,
    driverlicense: string,
    orderby: string,
    passport: string,
    telephone: string,
    virtualnum: string,
    mobile: string,
    totalcount: string
}

//  {
//     "result": "0", 
//     "errmsg": "成功", 
//     "officefax": "", 
//     "birthday": "", 
//     "sex": "1", 
//     "telephone2": "", 
//     "idtype": "1", 
//     "userid": "8afac2ed5754b9ed0157a2e5d5cd40f1",
//     "officialtype": "", 
//     "servicecontent": "", 
//     "city": "", 
//     "loginname": "yangyi233",
//     "username": "杨逸", 
//     "officerlicense": "", 
//     "useable": "1", 
//     "province": "", 
//     "permitlicense": "", 
//     "official": "", 
//     "companysize": "", 
//     "companypro": "", 
//     "companydesc": "", 
//     "homephone": "", 
//     "companyalias": "", 
//     "firmname": "", 
//     "authlevel": "2", 
//     "companytype": "", 
//     "orgcoding": "001006", 
//     "mobile2": "", 
//     "postcode": "", 
//     "homeaddress": "", 
//     "companyname": "", 
//     "nation": "01", 
//     "country": "", 
//     "officenum": "", 
//     "officeaddress": "", 
//     "headpicture": "", 
//     "idnum": "330324199110257793", 
//     "email": "", 
//     "driverlicense": "", 
//     "orderby": "4225854", 
//     "passport": "", 
//     "telephone": "", 
//     "virtualnum": "", 
//     "mobile": "13989723727", 
//     "totalcount": "17"
// }
